### ISSUE TITLE
Please update the app

### ISSUE THREAD

**Issue by ryecrow** [LanderlYoung/SonyDafaIsGood#2]
This app hasn't been updated for 8 months. Is the process of development stopped?

**Comment by LanderlYoung** [comment]
Of course not! Sony Dafa is Always GOOOOOOOOOOOOOOD!!!

**Comment by ryecrow** [comment]
23333

**Comment by LanderlYoung** [comment]
Be noticed, this project is still alive. God bless Dafa.

**Comment by ryecrow** [comment]
Dafa is watching you
